config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do 
    resources :comments
  end  
  get 'about', to: 'menu#about' 
  get 'help', to: 'menu#help'
  #post 'comments', to: 'comments#create'
  #resources :comments
  #get 'users/:id', to:'users#show', as: 'user'
  resources :users, only: [:show, :destroy]
  post 'likes', to: 'likes#create'
  post 'unlike', to: 'likes#destroy'
  
  #get 'posts/:post_title/comments', to:'comments#index', as: 'post_comments' 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
       #if user.admin?
       # can :manage, :all
       #else
       #  can :read, :all
       #end
    
    can :manage, Comment, user_id: user.id

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :text, presence: true, length: {minimum: 10}
	validates :post_id, presence: true
	validates :user_id, presence: true
	belongs_to :post
	belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	validates :post_id, uniqueness: {scope: :user_id} # 1 user may like 1 post
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :content, presence: true
	validates :title, presence: true
	has_many :comments, dependent: :destroy
	belongs_to :user
	has_many :likes, dependent: :destroy

	def likers
		names = likes.collect {|like| like.user.name} 
		names.join(', ')
	end	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments  
  has_many :likes 
  #
  def already_liked?(post_id)
  	likes.where(post_id: post_id).empty?
  end		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #Для редактирования пользователей 
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  private
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: :create
	load_and_authorize_resource
	def index
		#@post = Post.find_by(title: params[:post_title])
        #@comments = @post.comments #Comment.where(post_id: params[:post_id]) #find_by(post_id: params[:post_id])
        @comments = Comment.where(post_id: params[:post_id])   
    end
	def create
		#render text: params[:comment]
		#Comment.create(params[:comment]) #-- не пройдет по безопасности
		
		@comment = current_user.comments.new(comment_params)
		@comment.post_id = params[:post_id]
        
		if @comment.save

			redirect_to post_path(@comment.post_id),notice: "Your comment was saved!"
		else 
			session[:comment] = @comment.text
			redirect_to post_path(@comment.post_id),notice: "Could not save!"
			#@post = Post.find(@comment.post_id)
			#@comments = @post.comments
			#@likes = @post.likes
			#render 'posts/show'
		end	
	end	
  def destroy
  	
  	@comment = Comment.find(params[:id])
  	#post_id = @comment.post_id
  	@comment.destroy #if current_user.id == @comment.user_id
    respond_to do |format|
      flash[:warning] ='Comment was successfully destroyed.'	
      format.html { #redirect_to post_url(post_id), notice: 'Comment was successfully destroyed.' }
      redirect_to :back }
      format.json { head :no_content }
    
    end

  end
	def comment_params
		params.require(:comment).permit(:text, :post_id)  #post_id - из за валидации
	end
	      
end	

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create

		#not_liked = current_user.likes.where(post_id: params[:post_id]).empty?
		#if not_liked
		@like = current_user.likes.create(post_id: params[:post_id])		
		#end
		redirect_to post_path(params[:post_id])
	end	
	def destroy
		@like = current_user.likes.where(post_id: params[:post_id])	
		@like.destroy_all	
		redirect_to post_path(params[:post_id])
	end
end	

app/controllers/menu_controller.rb
class MenuController < ApplicationController
    def about
        
    end	
    def help

    end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    @comment = Comment.new(text: session[:comment])
    session[:comment] = ''
    @likes = @post.likes
  end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params) 
        flash[:success] = 'Post was successfully updated.'
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		#для порсмотра профайлов пользователей
		@user = User.find(params[:id])
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
    <p><%= comment.user.try(:name) || "Undefined" %> 
    :<%= comment.text %></p>
    <% if can? :destroy, comment #current_user.id == comment.user_id %>
    <%= link_to 'Destroy', post_comment_path(comment.post_id, comment.id), method: :delete%>
    <% end %>
<% end %>	

app/views/layouts/_header.html.erb
<!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'HOME', root_path, class: "navbar-brand" %>        
            
          </div>
          <div id="navbar" class="navbar-collapse collapse">
           
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'ABOUT', about_path %></li>
              <li><%= link_to 'HELP', help_path %></li>
              <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">PROFILE <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'My profile', user_path(current_user.id) %></li>
                  <li><%= link_to 'Edit profile', edit_user_registration_path%></li>
                   <!--удалить сессию-->
                <li><%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete %></li>  
              
                </ul>
              </li>
               <% else %>
                <li><%= link_to 'SIGN IN', new_user_session_path %></li>
                <li><%= link_to 'SIGN UP', new_user_registration_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class ="container">
<%= render 'layouts/header' %>

<% flash.each do |key, value| %>    
    <div class = "alert alert-<%= key %>" ><%= value %></div> 
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/menu/about.html.erb
<h1>About us</h1>

app/views/menu/help.html.erb
<h1>HELP</h1>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title, label: "Post name" %>
  <%= f.input :content %>
  <%= f.submit 'Save' , class: 'btn btn-primary'%>
<% end %>

app/views/posts/destroy.js.erb.js.erb
$('#<%= dom_id(@comment) %>').fadeOut();

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%#= notice %></p>
HELLO
<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
    <% @posts.each do |post| %>
      
        <h1><%= link_to post.title, post %>  
        by
        <%= post.user.name  if post.user_id.present? %></h1>
        <p><%= post.content %></p>
        <!--
        <%= link_to 'More', post %>        
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        -->
      
    <% end %>


<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <%= @post.title %>
</p>

<p>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<!-- проверка на логин  -->
<% if user_signed_in? %>

<% if current_user.already_liked?(@post.id) %>
<%= link_to 'Like', likes_path(post_id: @post.id), method: :post %>
<% else %>
<%= link_to 'Unlike', unlike_path(post_id: @post.id), method: :post %>
<% end %>
<% end %>
<%= @likes.count %> 
<%= @post.likers %>

<h3>Leave a comment </h3>
<!--форма для ввода комментариев -->
<%= simple_form_for [@post, @comment] do |f| %>
 <!--<%= f.label :author %>
 <%= f.text_field :author %>
 <%= f.label :comment %>-->
 <% if user_signed_in? %>
 <%= current_user.name%>: 
 <% end %>
 <%= f.input :text %>
 <%#= f.association :post %> <!--для выбора постов-->
 <%#= f.input :post_id, as: :hidden, input_html: {value: @post.id} %> 
 <%#= f.input :post_id, as: :hidden, value: @post.id %> <!--передаем для comments_controller.rb-->

 <%= f.submit 'Send', class: 'btn btn-primary' %>
<% end %>
<h3><%= link_to "All comments", post_comments_path(@post.id) %>
: <%= @comments.count %></h3>
<% @comments.each do |comment| %>
    <p><%= comment.user.try(:name) || "Undefined" %> 
    :<%= comment.text %></p>
    <% if can? :destroy, comment #current_user.id == comment.user_id %>
    <%= link_to 'Destroy', post_comment_path(@post.id, comment.id), method: :delete%>
    <% end %>
<% end %>	

app/views/users/show.html.erb
Hello <%= @user.name%>